.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/format.yml
=> add workflows

logic/GameClass/GameObj/Bullets/BulletFactory.cs, logic/GameClass/GameObj/Ship.cs, logic/GameClass/GameObj/Team.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs
Add some interfaces in Game.cs
=> feat: ✨ add some interfaces in game

logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Map/Map.cs, logic/GameClass/GameObj/Map/MapReader.cs, logic/GameClass/GameObj/Team.cs, logic/Gaming/Game.cs, logic/Preparation/Interface/IHome.cs
Determine `TeamID` in previous and then bind `Team` to it instead of the opposite
=> Revision for Home & Team

dependency/Dockerfile/Dockerfile_base, dependency/Dockerfile/Dockerfile_cpp, dependency/Dockerfile/Dockerfile_run, dependency/Dockerfile/README.md
=> feat: :sparkles: Add Dockerfile

logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Areas/Wormhole.cs, logic/GameClass/GameObj/Bullet.cs, logic/GameClass/GameObj/Bullets/Arc.cs, logic/GameClass/GameObj/Bullets/Laser.cs, logic/GameClass/GameObj/Bullets/Missile.cs, logic/GameClass/GameObj/Bullets/NullBullet.cs, logic/GameClass/GameObj/Bullets/Plasma.cs, logic/GameClass/GameObj/Bullets/Shell.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Gaming/ShipManager.cs, logic/Preparation/Utility/EnumType.cs
=> feat: ✨ realize attack

logic/Client/GameStatusBar.xaml.cs
=> 🔥 delete: comment MessageOfBuilding for proto update

logic/Client/MainPage.xaml.cs, logic/logic.sln
=> fix(logic): :bug: Include Playback.csproj into logic.sln

logic/Server/GameServer.cs, logic/Server/RpcServices.cs
=> fix(Server): :bug: Fix wrong conflicts resolution #60

dependency/proto/Message2Server.proto, dependency/proto/Services.proto, logic/GameClass/GameObj/Areas/Resource.cs, logic/GameClass/GameObj/Modules/Civil/CivilArmor.cs, logic/GameClass/GameObj/Modules/Civil/CivilConstructor.cs, logic/GameClass/GameObj/Modules/Civil/CivilProducer.cs, logic/GameClass/GameObj/Modules/Civil/CivilShield.cs, logic/GameClass/GameObj/Modules/Civil/CivilWeapon.cs, logic/GameClass/GameObj/Modules/Flag/FlagArmor.cs, logic/GameClass/GameObj/Modules/Flag/FlagConstructor.cs, logic/GameClass/GameObj/Modules/Flag/FlagProducer.cs, logic/GameClass/GameObj/Modules/Flag/FlagShield.cs, logic/GameClass/GameObj/Modules/Flag/FlagWeapon.cs, logic/GameClass/GameObj/Modules/ModuleFactory.cs, logic/GameClass/GameObj/Modules/War/WarArmor.cs, logic/GameClass/GameObj/Modules/War/WarShield.cs, logic/GameClass/GameObj/Modules/War/WarWeapon.cs, logic/GameClass/GameObj/MoneyPool.cs, logic/GameClass/GameObj/Ship.cs, logic/GameClass/GameObj/Team.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs, logic/Gaming/ShipManager.cs, logic/Preparation/Interface/IMoneyPool.cs, logic/Preparation/Utility/GameData.cs, logic/Server/RpcServices.cs
Added class MoneyPool to share Money & Score between ships
=> feat: ✨ add MoneyPool to share Money & Score between ships

dependency/proto/Services.proto, logic/ClientTest/ClientTest.csproj, logic/ClientTest/Program.cs, logic/Server/GameServer.cs, logic/Server/RpcServices.cs
=> Add DEBUG console log & revise server

logic/Client/MainPage.xaml, logic/Client/MainPage.xaml.cs
=> feat: ✨ update new proto message

interface/Assets/Scenes/SampleScene.unity, interface/ProjectSettings/AudioManager.asset, interface/ProjectSettings/ClusterInputManager.asset, interface/ProjectSettings/DynamicsManager.asset, interface/ProjectSettings/EditorBuildSettings.asset, interface/ProjectSettings/EditorSettings.asset, interface/ProjectSettings/GraphicsSettings.asset, interface/ProjectSettings/InputManager.asset, interface/ProjectSettings/MemorySettings.asset, interface/ProjectSettings/NavMeshAreas.asset, interface/ProjectSettings/NetworkManager.asset, interface/ProjectSettings/PackageManagerSettings.asset, interface/ProjectSettings/Physics2DSettings.asset, interface/ProjectSettings/PresetManager.asset, interface/ProjectSettings/ProjectSettings.asset, interface/ProjectSettings/ProjectVersion.txt, interface/ProjectSettings/QualitySettings.asset, interface/ProjectSettings/SceneTemplateSettings.json, interface/ProjectSettings/ShaderGraphSettings.asset, interface/ProjectSettings/TagManager.asset, interface/ProjectSettings/TimeManager.asset, interface/ProjectSettings/URPProjectSettings.asset, interface/ProjectSettings/UnityConnectSettings.asset, interface/ProjectSettings/VFXManager.asset, interface/ProjectSettings/VersionControlSettings.asset, interface/ProjectSettings/XRPackageSettings.asset, interface/ProjectSettings/XRSettings.asset
=>  chore: 🚀 Added global universal rendering pipelines and shader graphs and introduced several related packages .

.github/workflows/format.yml, interface/Assets/Scripts/Debugger.cs, interface/Assets/Scripts/Live/MessageReceiverLive.cs, interface/Assets/Scripts/Manager/MapControl.cs, interface/Assets/Scripts/Manager/MessageManager.cs, interface/Assets/Scripts/Manager/ObjectCreater.cs, interface/Assets/Scripts/Manager/RendererControl.cs, interface/Assets/Scripts/MapControl.cs, interface/Assets/Scripts/MessageManager.cs, interface/Assets/Scripts/ObjectCreater.cs, interface/Assets/Scripts/ParaDefine.cs, interface/Assets/Scripts/Play/MessageReceiverPlay.cs, interface/Assets/Scripts/PlayerControl.cs, interface/Assets/Scripts/RendererControl.cs, interface/Assets/Scripts/base/Singleton.cs, interface/Assets/Scripts/base/SingletonDontDestory.cs, interface/Assets/Scripts/base/SingletonMono.cs
=> ci: :sparkles: add format-check for interface

.github/preProcess/MauiEnvConfig.csx, .github/workflows/build.yml, .github/workflows/format.yml, installer/MauiProgram.cs, installer/Model/Downloader.cs, installer/Model/EEsast.cs, installer/Model/Local_Data.cs, installer/Page/LoginPage.xaml, installer/Program.cs, installer/ViewModel/Common.cs, installer/ViewModel/LoginViewModel.cs, installer/ViewModel/MainViewModel.cs
完善了Downloader接口，在Viewmodel中添加了指向Downloader的访问器。
=> Downloader封装完毕。

installer/MauiProgram.cs, installer/Model/Downloader.cs, installer/Model/EEsast.cs, installer/Model/Local_Data.cs, installer/Model/Logger.cs, installer/Model/Tencent_Cos.cs
1. installer文件日志系统全覆盖，新增日志每月打包功能
2. 修复了重新安装路径与已安装路径重复时程序的错误表现
=> build: :test_tube: Log system in installer updated.

installer/Model/Downloader.cs, installer/Model/EEsast.cs, installer/Model/Helper.cs, installer/Model/Local_Data.cs, installer/Model/Tencent_Cos.cs, installer/Page/InstallPage.xaml, installer/ViewModel/InstallViewModel.cs
=> fix: :bug: Fixed some unexpected bugs on installer page.

dependency/MapGenerator/assets/js/map.js, logic/Gaming/Game.cs
remove strong reliance on birthPoint when adding a ship
=> fix: :bug: remove strong reliance on birthPoint when adding a ship

logic/ClientTest/Program.cs, logic/Gaming/Game.cs, logic/Server/ArgumentOptions.cs, logic/Server/GameServer.cs, logic/Server/PlaybackServer.cs, logic/Server/Properties/launchSettings.json, logic/Server/RpcServices.cs
Server 终于暂时正常了！
为什么先前不正常呢？是因为 Grid 和 Cell 的 XY 混用（mentioned in #58）导致数组越界了！
此外修改了一些比赛设定
=> fix: :bug: let Server run basically

installer/Model/Downloader.cs, installer/Model/Local_Data.cs
=> fix: :bug: Fixed some bug and add version id to local_data.

logic/Server/ArgumentOptions.cs, logic/Server/GameServer.cs, logic/Server/Properties/launchSettings.json
=> fix issues which cannot add player

installer/Model/Logger.cs, installer/Page/InstallPage.xaml, installer/ViewModel/InstallViewModel.cs
=> Exception List in Installer

logic/Server/RpcServices.cs
=> fix: 🐛 fix server playerNum constantly=10 bug

CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/logic.py
=> fix(PyAPI): :bug: fix mismatch with proto

logic/Gaming/Game.cs, logic/Server/CopyInfo.cs
=> fix small bugs

CAPI/python/PyAPI/AI.py, logic/Client/ViewModel/GeneralViewModel.cs, logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Areas/Shadow.cs, logic/GameClass/GameObj/Map/Map.cs, logic/GameClass/GameObj/Ship.cs, logic/GameEngine/MoveEngine.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs
=> fix: 🐛 add place to map

CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/logic.py, CAPI/python_exp/PyAPI/DebugAPI.py, CAPI/python_exp/PyAPI/logic.py
=> fix wrong `ShipPlay` in `TeamDebugAPI` & improve log file name

logic/Client/Model/DrawCircLabel.cs, logic/Client/README.md, logic/Client/Util/UtilFunctions.cs, logic/Client/Util/UtilInfo.cs, logic/Client/View/MainPage.xaml, logic/Client/View/MainPage.xaml.cs, logic/Client/ViewModel/GeneralViewModel.cs, logic/Client/ViewModel/MapViewModel.cs
=> README: 📝 Added Readme for client

logic/Client/ViewModel/GeneralViewModel.cs, logic/GameClass/GameObj/Areas/WormholeCell.cs, logic/GameClass/GameObj/Base.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs, logic/Preparation/Utility/GameData.cs, logic/Server/CopyInfo.cs, logic/Server/GameServer.cs
=> fix: :bug: numerical issues

logic/Client/App.xaml, logic/Client/Util/UtilInfo.cs, logic/Client/View/MainPage.xaml, logic/Client/View/MainPage.xaml.cs, logic/Client/ViewModel/GeneralViewModel.cs, logic/Client/ViewModel/MapViewModel.cs
=> feat: ✨ beautify the debugger

logic/Client/Util/UtilFunctions.cs, logic/Client/View/MainPage.xaml, logic/Client/View/MainPage.xaml.cs, logic/Client/ViewModel/GeneralViewModel.cs, logic/Client/ViewModel/MapViewModel.cs, logic/Server/ArgumentOptions.cs
=> feat: ✨ Add some commands & fix spectator bug

installer/Data/DownloadReport.cs, installer/Model/Downloader.cs, installer/Model/Local_Data.cs, installer/Model/Logger.cs, installer/Model/Tencent_Cos.cs
1. Fixed some bugs in log system.
2. Add new feature: download report in Data/DownloadReport.cs
=> Log system updated and add download report.

logic/Preparation/Utility/Value/SafeValue/AtomicInt.cs, logic/Preparation/Utility/Value/SafeValue/ObjPool.cs
=> chore(SafeValue): :lock: fix some warnings

logic/Client/Client.csproj, logic/Client/Client.sln, logic/Client/PlaybackClient.cs, logic/Client/ViewModel/GeneralViewModel.cs
=> feat: ✨ add playback mode (not tested!)

dependency/proto/Message2Clients.proto, logic/Client/ViewModel/GeneralViewModel.cs, logic/Client/ViewModel/MapViewModel.cs, logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Areas/Resource.cs, logic/GameClass/GameObj/Areas/Wormhole.cs, logic/GameClass/GameObj/Map/Map.cs, logic/GameClass/GameObj/MoneyPool.cs, logic/Gaming/ActionManager.cs, logic/Server/CopyInfo.cs
=> fix: :bug: wormhole id

logic/Preparation/Utility/Value/SafeValue/LockedValue/InRangeTimeBased.cs, logic/Server/RpcServices.cs
=> delete a log in RPC

CAPI/python_exp/.gitignore, CAPI/python_exp/.vscode/launch.json, CAPI/python_exp/.vscode/settings.json, CAPI/python_exp/PyAPI/logic.py, CAPI/python_exp/playback.py, logic/Server/GameServer.cs, logic/Server/RpcServices.cs, playback/Playback/MessageReader.cs, playback/Playback/MessageWriter.cs
=> playback flush every 500 msg

logic/Server/RpcServices.cs
=> fix: :bug: Server阻塞

installer/Model/Downloader.cs, installer/Model/EEsast.cs, installer/Model/Local_Data.cs, installer/Page/LoginPage.xaml, installer/ViewModel/LoginViewModel.cs
=> Login page updated.

installer/ViewModel/LaunchViewModel.cs
=> feat: Add player code execution

installer/Data/ConfigFileData.cs, installer/Data/DownloadReport.cs, installer/Model/Downloader.cs, installer/Model/Tencent_Cos.cs, installer/Page/InstallPage.xaml, installer/Services/FileService.cs, installer/ViewModel/BaseViewModel.cs, installer/ViewModel/InstallViewModel.cs
Fixed some errors. Now the progress bar of downloader can run correctly.
=> Progress bar works now

logic/Server/RpcServices.cs
=> fix(Server): :bug: ship should be found both in `PlayerId` & `TeamId`

installer/Data/ConfigFileData.cs, installer/Page/InstallPage.xaml, installer/Page/LaunchPage.xaml, installer/Platforms/Windows/Package.appxmanifest, installer/ViewModel/InstallViewModel.cs, installer/ViewModel/LaunchViewModel.cs, installer/installer.csproj, logic/Server/RpcServices.cs
=> Verify Launcher

CAPI/cpp/API/include/structures.h, CAPI/cpp/API/src/AI.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/logic.py, logic/Server/RpcServices.cs
- [√] 您的代码是否能够编译通过？
- [ √] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI7/pulls) 中是否有与你的贡献功能相同的更改？
- [ √] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI7/blob/dev/CODE_OF_CONDUCT.md)？
- [ √] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI7#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> fix the problem that client didn't receive gameMap

logic/Gaming/ShipManager.cs
=> fix: :bug: activate ship sub money

logic/Client/ViewModel/MapViewModel.cs
=> fix: 🐛 fix wormhole drawing bug

logic/Client/Interact/Command.cs
=> fix: 🚑 fix connection with installer

CAPI/cpp/API/src/AI.cpp, CAPI/python/PyAPI/State.py, CAPI/python/PyAPI/logic.py
=> fix: 🐛 fix a wrong condition in a if sentence

installer/AppShell.xaml, installer/Page/HelpPage.xaml, installer/ViewModel/HelpViewModel.cs, installer/ViewModel/InstallViewModel.cs, installer/ViewModel/LaunchViewModel.cs
1. Close the login page
2. Add scroll bar in help page
3. Fix the launch of python api
=> Installer v1.0.1

installer/AppShell.xaml, installer/Data/ConfigFileData.cs, installer/Data/MD5FileData.cs, installer/Model/Downloader.cs, installer/Model/Local_Data.cs, installer/Model/Tencent_Cos.cs, installer/ViewModel/HelpViewModel.cs, installer/ViewModel/LaunchViewModel.cs
1. 新增Installer自更新和选手代码更新
2. 分离启动部分代码
=> Self-update installer finished.

logic/GameClass/GameObj/Ship.cs, logic/Gaming/ActionManager.cs
=> fix(Logic): :lock: make the ShipState thread-safe

logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Gaming/ShipManager.cs, logic/Preparation/Utility/Value/SafeValue/LockedValue/InTheRange.cs
=> chore(Logic): :lock: do some chore

CAPI/cpp/API/src/AI.cpp, CAPI/python/PyAPI/AI.py
=> update AI.cpp and AI.py

installer/Data/MD5FileData.cs, installer/Model/Logger.cs
=> installer: Prevent while loops from consuming a large amount of CPU

installer/Model/Downloader.cs
=> fix: 🐛 Fix the bug that version hasn't been updated after downloading new package.

CAPI/python/PyAPI/logic.py
=> fix: :bug: Update logic.py

logic/GameClass/GameObj/Ship.cs
=> fix: 🐛 installModule return wrong money

logic/Gaming/AttackManager.cs, logic/Gaming/ShipManager.cs
=> fix: :bug: attack teammate

logic/GameClass/GameClassLogging.cs, logic/GameClass/GameObj/Map/Map.cs, logic/GameClass/GameObj/Ship.cs, logic/GameEngine/GameEngineLogging.cs, logic/GameEngine/MoveEngine.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Gaming/GamingLogging.cs, logic/Gaming/ShipManager.cs, logic/Preparation/Utility/GameData.cs, logic/Preparation/Utility/UtilityLogging.cs, logic/Preparation/Utility/Value/SafeValue/LockedValue/LockedValue.cs, logic/Preparation/Utility/Value/SafeValue/MyTimer.cs, logic/Preparation/Utility/Value/SafeValue/TimeBased.cs, logic/Server/GameServer.cs, logic/Server/PlaybackServer.cs, logic/Server/ServerLogging.cs
=> add `BulletLogInfo` & `AutoLogInfo`

installer/Manual.md, installer/Page/DebugPage.xaml, installer/ViewModel/DebugViewModel.cs, installer/ViewModel/LaunchViewModel.cs
=> perf: 👽 Add check of spectator id

installer/Data/MD5FileData.cs, installer/Model/Downloader.cs
=> feat: ⚡ Compress the logs before too big to analyse.

logic/Server/ArgumentOptions.cs, logic/Server/GameServer.cs
=> new features

logic/Preparation/Utility/Value/SafeValue/Atomic.cs, logic/Preparation/Utility/Value/SafeValue/AtomicInt.cs, logic/Preparation/Utility/Value/SafeValue/LockedValue/InTheRange.cs, logic/Preparation/Utility/Value/SafeValue/LockedValue/LockedDouble.cs, logic/Preparation/Utility/Value/SafeValue/LockedValue/PositiveV.cs, logic/Preparation/Utility/Value/SafeValue/TimeBased.cs, logic/Preparation/Utility/Value/ValueInterface/IReturnClass.cs
=> fix(SafeValue): ✨ make SafeValue can Equal

CAPI/python/PyAPI/utils.py
=> fix(PyAPI): :bug: add Energy & HomeHp copying from proto to `gameInfo`

logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Base.cs, logic/GameClass/GameObj/GameObj.cs, logic/Preparation/Utility/Value/SafeValue/Atomic.cs, logic/Preparation/Utility/Value/SafeValue/ObjPool.cs
=> fix(Logic): :bug: fix the bug about the HP of the home

CAPI/cpp/API/src/logic.cpp
=> fix: :bug: fix a careless bug in sendmessage

logic/Server/GameServer.cs, logic/Server/HttpSender.cs
=> fix:Httpsender

dependency/shell/run.sh, logic/Server/GameServer.cs, logic/Server/HttpSender.cs
=> fix(http): ContestResult type

dependency/shell/run.sh, logic/Server/GameServer.cs, logic/Server/HttpSender.cs
=> fix: ContestResult type

dependency/shell/run.sh
=> fix: run.sh retry times

dependency/Dockerfile/Dockerfile_run_client
=> try: run.sh > client.log

dependency/Dockerfile/Dockerfile_run_client, dependency/shell/run.sh
=> try: client log

logic/GameClass/GameObj/Base.cs
=> fix: :bug: Home add money after destroyed

logic/Client/ViewModel/GeneralViewModel.cs
=> fix: 🐛 [playback] No changes but it works, don't know why

installer/Data/MD5FileData.cs, installer/ViewModel/DebugViewModel.cs
=> fix: 🐛 Fix the bug caused by low priority of ?? operator.

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/constants.py, CAPI/python/PyAPI/logic.py
=> Change GetConstructionHp to GetConstructionState to return building team_id information. And fix bug with construction information pair

CAPI/cpp/API/include/utils.hpp, CAPI/python/PyAPI/utils.py
=> fix viewRange

dependency/proto/Services.proto, logic/GameClass/GameObj/Areas/Home.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs, logic/Server/RpcServices.cs
发现通信组没有实现修复虫洞功能，遂加之。C++/Python接口尚未添加。
再添加修复大本营功能。
=> feat: :sparkles: add Repair

dependency/proto/Services.proto, logic/GameClass/GameObj/Areas/Home.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs, logic/Server/RpcServices.cs
=> Revert "feat: :sparkles: add Repair"

.github/workflows/deploy.yml, dependency/deploy/Program.cs, installer/Data/MD5FileData.cs, installer/ViewModel/DebugViewModel.cs, logic/Client/ViewModel/GeneralViewModel.cs
1. 在Pull request中移除了不必要的deploy流程
2. 检测到installer version升级时自动发布installer
3. 将api输出至文件
=> chore: 🔖 Update installer to v1.1.0.1

logic/Gaming/ActionManager.cs, logic/Preparation/Utility/Logger.cs
=> fix(Logger): :bug: too many threads in `Logger` & ensure `AddMoneyNaturally`

logic/Server/RpcServices.cs
Spectator屏蔽NewsMessage应创建一个currentGameInfo的深拷贝，不能影响其他Player的消息接收
=> Urgent:Spectator Message Block

dependency/proto/Services.proto, logic/GameClass/GameObj/Areas/Home.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs, logic/Server/RpcServices.cs
=> feat: copy PR #358

CAPI/cpp/proto/Message2Clients.pb.cc, CAPI/cpp/proto/Message2Clients.pb.h, CAPI/cpp/proto/Message2Server.pb.cc, CAPI/cpp/proto/Message2Server.pb.h, CAPI/cpp/proto/Services.grpc.pb.cc, CAPI/cpp/proto/Services.grpc.pb.h, CAPI/cpp/proto/Services.pb.cc, CAPI/python/PyAPI/Interface.py
=> feat: :sparkles: update protobuf file in cpp

CAPI/cpp/API/include/utils.hpp
=> fix: 🐛 fix overflow bug in logic.HaveView()

CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/logic.cpp
=> align data type in CAPI

logic/GameClass/GameObj/Areas/Construction.cs, logic/Gaming/AttackManager.cs
=> fix: :bug: construction activate

logic/GameClass/GameObj/Areas/Asteroid.cs, logic/GameClass/GameObj/Areas/Construction.cs, logic/GameClass/GameObj/Areas/Home.cs, logic/GameClass/GameObj/Areas/NullArea.cs, logic/GameClass/GameObj/Areas/OutOfBoundBlock.cs, logic/GameClass/GameObj/Areas/Resource.cs, logic/GameClass/GameObj/Areas/Ruin.cs, logic/GameClass/GameObj/Areas/Shadow.cs, logic/GameClass/GameObj/Areas/WormholeCell.cs, logic/GameClass/GameObj/BombedBullet.cs, logic/GameClass/GameObj/Bullet.cs, logic/GameClass/GameObj/GameObj.cs, logic/GameClass/GameObj/Ship.cs, logic/GameEngine/CollisionChecker.cs, logic/GameEngine/MoveEngine.cs, logic/Gaming/AttackManager.cs, logic/Preparation/Interface/IGameObj.cs, logic/Preparation/Interface/IMovable.cs
=> feat: :sparkles: bullet can attack wormhole

CAPI/cpp/API/include/constants.h, CAPI/python/PyAPI/constants.py
=> feat: :memo: Update constant

logic/GameClass/GameObj/Areas/Construction.cs, logic/Gaming/AttackManager.cs
=> fix: 🐛 wormhole keep killing, construction not zero

logic/Gaming/AttackManager.cs
=> fix: :bug: wormhole do not kill

logic/GameClass/GameObj/Map/Map.cs
=> fix: :bug: repairwormhole

logic/GameClass/GameObj/Areas/Construction.cs
=> fix: :bug: factory die too many times
